# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/maintreebd
spring.datasource.username=root
spring.datasource.password=

# Mail Configuration
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=noreply@maintree.app
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update

# Application Configuration
app.default.role=CLIENTE
app.token.expiration.ms=3600000

# Static Content
spring.web.resources.static-locations=classpath:/static/
server.port=8081