# Database Configuration
db.url=jdbc:mysql://localhost:3306/maintreebd
db.user=root
db.password=

# Mail Configuration
mail.host=localhost
mail.port=1025
mail.username=noreply@maintree.app
mail.password=
mail.auth=false

# Application Configuration
app.default.role=CLIENTE
app.token.expiration.ms=3600000

